### PR TITLE
Set the PP threshold as a constant variable

### PR DESCRIPTION
**Pull request by ireneisdoomed**
~There is a bug in the L2G step where the datasets are prepared to later be used.~

~According to the documentation and the L2G manuscript, the credible sets are filtered to keep variants with a posterior probability higher than 0.01%. This contraint is later used to extract the features from colocalisation results, and several other annotation.~

~However when processing the credible sets, a threshold of 0.1% is used due to a typo. I've changed that to apply what our docs say.~

This PR only applies changes for better handling of how the threshold is applied. Instead of hardcoding the value in each function, it is defined in a constant variable that is then passed as an argument.

### CODE REVIEW

**Comment by Jeremy37** [comment]
Wouldn't it make more sense to change the documentation to reflect what is in the code, and has been the implementation for the past few years?
The threshold is arbitrary, but I would argue that 0.1% is reasonable - credible sets with hundreds of variants or more are not very useful. Also, note that this threshold (0.1%) is used in the fine-mapping pipeline (https://github.com/opentargets/genetics-finemapping/blob/ed7146900518562f4513b6e24749a9089412d039/configs/analysis.config.yaml#L20), so there won't be any variants given to L2G with PP < 0.1%.

**Comment by ireneisdoomed** [comment]
@Jeremy37 Well, to me it makes more sense that the code reproduces what it is described in the documentation mostly because I assume there have been more eyes on the publication than on the script. At the same time, great to hear that 0.1% is not too stringent.

The threshold in the credible set calculation isn't however applied in the LD expansion, so we do have variants with a PP lower than 0.1%. The features extracted from them have already a significant weight in the model, so maybe we don't want to flex this threshold.

**Comment by Jeremy37** [comment]
The NatGen publication says 0.1%.

**Comment by ireneisdoomed** [comment]
@Jeremy37 Ok, sorry, I read the section `Derivation of L2G prioritization features` and I was misled.
> We converted variant-centric scores into L2G scores by aggregating over credible variants identified through fine mapping. For GWASs with summary statistics available, we used ABF credible sets; otherwise, we used LD-based PICS credible sets. We implemented two complementary methods for aggregating over credible sets. First, we took a weighted sum of scores across all variants identified by fine mapping (**PP > 0.01%**) using PP of causality as weights (equation (1)).

It is true that the one given in the method describing how the fine mapping datasets were extracted says 0.1%.
> We considered any variant with a PP > 0.1% as being in the credible set.

If you are happy with the set value I can close the PR.

**Review by DSuveges — APPROVED** [review]
Looks good. All makes sense.

**Pull request merged**
